name: ðŸ§ª Test Self-Hosted Runner

on:
  push:
    branches:
      - e2e-integrate
jobs:
  package:
    runs-on: self-hosted
    container:
      image: node:20-bullseye
    steps:
      - name: ðŸ“¦ Checkout source code
        uses: actions/checkout@v4

      - name: ðŸ§© Prepare source
        run: |
          npm install
          cd packages/postgres-query-builder
          npm run compile
          cd ../evershop
          npm pack
          VERSION=$(node -p "require('./package.json').version")
          FILE_NAME="evershop-evershop-$VERSION.tgz"
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          echo "âœ… Built package: $FILE_NAME"

      - name: ðŸ“¤ Copy package to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SELF_HOSTED_RUNNER_102_VPS_IP }}
          username: ${{ secrets.SELF_HOSTED_RUNNER_102_USER }}
          key: ${{ secrets.SELF_HOSTED_RUNNER_102_PRIVATE_KEY }}
          port: 22
          source: "${{ steps.build.outputs.file_name }}"
          target: "/home/github-runner/e2e-ecommerce-evershop/source"

      - name: ðŸš€ Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SELF_HOSTED_RUNNER_102_VPS_IP }}
          username: ${{ secrets.SELF_HOSTED_RUNNER_102_USER }}
          key: ${{ secrets.SELF_HOSTED_RUNNER_102_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/github-runner/e2e-ecommerce-evershop/source
            rm -rf ./node_modules package-lock.json
            npm install
            npm install "file:./${{ env.FILE_NAME }}"
            npm run build
